/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.aula.Aula;
import bodyfitness.aula.CategoriaDeAula;
import bodyfitness.dao.AulaDAO;
import bodyfitness.dao.CategoriaDeAulaDAO;
import bodyfitness.dao.FuncionarioDAO;
import bodyfitness.pessoas.funcionarios.Funcionario;
import bodyfitness.util.UtilBodyfitness;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class CadastroAula extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAula
     */
    public CadastroAula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroAulaPanel = new javax.swing.JPanel();
        professorCBox = new javax.swing.JComboBox<>();
        horarioInicioCBox = new javax.swing.JComboBox<>();
        categoriaCBox = new javax.swing.JComboBox<>();
        dataTField = new javax.swing.JFormattedTextField();
        horarioTerminoCBox = new javax.swing.JComboBox<>();
        clienteIdTField = new javax.swing.JTextField();
        cadastroButton = new javax.swing.JButton();
        professorLabel = new javax.swing.JLabel();
        caulaLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        horarioTerminoLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        idTField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CadastroAulaPanel.setLayout(null);

        professorCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" "}));
        CadastroAulaPanel.add(professorCBox);
        professorCBox.setBounds(210, 170, 260, 50);

        horarioInicioCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" "}));
        CadastroAulaPanel.add(horarioInicioCBox);
        horarioInicioCBox.setBounds(670, 170, 250, 50);

        CadastroAulaPanel.add(categoriaCBox);
        categoriaCBox.setBounds(220, 370, 250, 50);

        try {
            dataTField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CadastroAulaPanel.add(dataTField);
        dataTField.setBounds(630, 270, 290, 50);

        horarioTerminoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" "}));
        CadastroAulaPanel.add(horarioTerminoCBox);
        horarioTerminoCBox.setBounds(690, 370, 230, 50);
        CadastroAulaPanel.add(clienteIdTField);
        clienteIdTField.setBounds(190, 270, 280, 50);

        cadastroButton.setText("Cadastrar");
        CadastroAulaPanel.add(cadastroButton);
        cadastroButton.setBounds(510, 470, 80, 50);

        professorLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        professorLabel.setForeground(new java.awt.Color(254, 254, 254));
        professorLabel.setText("Professor :");
        CadastroAulaPanel.add(professorLabel);
        professorLabel.setBounds(80, 170, 120, 50);

        caulaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        caulaLabel.setForeground(new java.awt.Color(254, 254, 254));
        caulaLabel.setText("Categoria :");
        CadastroAulaPanel.add(caulaLabel);
        caulaLabel.setBounds(80, 370, 130, 50);

        horarioLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        horarioLabel.setForeground(new java.awt.Color(254, 254, 254));
        horarioLabel.setText("Horário Início :");
        CadastroAulaPanel.add(horarioLabel);
        horarioLabel.setBounds(510, 170, 160, 50);

        horarioTerminoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        horarioTerminoLabel.setForeground(new java.awt.Color(254, 254, 254));
        horarioTerminoLabel.setText("Horário Término :");
        CadastroAulaPanel.add(horarioTerminoLabel);
        horarioTerminoLabel.setBounds(490, 370, 200, 50);

        dataLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(254, 254, 254));
        dataLabel.setText("Data :");
        CadastroAulaPanel.add(dataLabel);
        dataLabel.setBounds(540, 270, 80, 50);

        clienteLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        clienteLabel.setForeground(new java.awt.Color(254, 254, 254));
        clienteLabel.setText("Cliente :");
        CadastroAulaPanel.add(clienteLabel);
        clienteLabel.setBounds(80, 270, 100, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Cadastro de Aulas\n");
        CadastroAulaPanel.add(header);
        header.setBounds(350, 20, 310, 60);
        CadastroAulaPanel.add(idTField);
        idTField.setBounds(190, 470, 280, 50);

        idLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(254, 254, 254));
        idLabel.setText("ID :");
        CadastroAulaPanel.add(idLabel);
        idLabel.setBounds(130, 470, 50, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        CadastroAulaPanel.add(image);
        image.setBounds(-180, -250, 1971, 1540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastroAulaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastroAulaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        /*professorCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorCBoxActionPerformed(evt);
            }
        });*/
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> professores = dao.consultarPorCargo("professor");
        this.professorCBox.removeAll();
        for (Funcionario c : professores) {
            this.professorCBox.addItem(c.getId().toString() + " - " + c.getNome());
        }
        this.horarioInicioCBox.removeAllItems();
        this.horarioInicioCBox.addItem("08:00:00");
        this.horarioInicioCBox.addItem("09:00:00");
        this.horarioInicioCBox.addItem("10:00:00");
        this.horarioInicioCBox.addItem("13:00:00");
        this.horarioInicioCBox.addItem("14:00:00");
        this.horarioInicioCBox.addItem("15:00:00");
        this.horarioTerminoCBox.removeAllItems();
        this.horarioTerminoCBox.addItem("09:00:00");
        this.horarioTerminoCBox.addItem("10:00:00");
        this.horarioTerminoCBox.addItem("11:00:00");
        this.horarioTerminoCBox.addItem("12:00:00");
        this.horarioTerminoCBox.addItem("14:00:00");
        this.horarioTerminoCBox.addItem("15:00:00");
        this.horarioTerminoCBox.addItem("16:00:00");

        CategoriaDeAulaDAO c = new CategoriaDeAulaDAO();
        List<CategoriaDeAula> categoriasDeAula = c.consultarTodos();
        categoriaCBox.removeAll();
        for (CategoriaDeAula ca : categoriasDeAula) {
            this.categoriaCBox.addItem(ca.getCategoria());
        }

        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    cadastroButtonActionPerformed(evt);
                } catch (ParseException ex) {
                    Logger.getLogger(CadastroAula.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    public void professorCBoxActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {
        Date data = new Date();
        String dataIni = null;
        String datafin = null;
        boolean erro = false;
        if (!this.dataTField.getText().matches("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$")) {
            JOptionPane.showMessageDialog(null, "Erro na data", "Erro", JOptionPane.ERROR_MESSAGE);
            erro = true;
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            data = formato.parse(this.dataTField.getText());
            if (UtilBodyfitness.getDiferencaEmAnos(data) < 0) {
                JOptionPane.showMessageDialog(null, "Erro na data", "Erro", JOptionPane.ERROR_MESSAGE);
                erro = true;
            }
        }
        if (this.horarioInicioCBox.getSelectedIndex() > this.horarioTerminoCBox.getSelectedIndex()) {
            JOptionPane.showMessageDialog(null, "Erro no horário", "Erro", JOptionPane.ERROR_MESSAGE);
            erro = true;
        } else {
            SimpleDateFormat formato = new SimpleDateFormat("HH:MM:SS");
            dataIni = this.horarioInicioCBox.getSelectedItem().toString();
            datafin = this.horarioTerminoCBox.getSelectedItem().toString();
        }
        if (erro == false) {
            Aula aula = new Aula(); 
            if(!this.idTField.getText().isEmpty()) {
                aula.setId(Long.valueOf(this.idTField.getText()));
            }
            FuncionarioDAO fdao = new FuncionarioDAO();
            CategoriaDeAulaDAO cdao = new CategoriaDeAulaDAO();
            aula.setProfessor(fdao.consultaPorId(Long.valueOf(this.professorCBox.getSelectedItem().toString().split(" - ")[0])));
            aula.setCategoria(cdao.consultarPorNome(this.categoriaCBox.getSelectedItem().toString()));
            aula.setDia(data);
            aula.setHoraDeInicio(dataIni);
            aula.setHoraDeTermino(datafin);
            AulaDAO adao = new AulaDAO();
            adao.persist(aula);
            JOptionPane.showMessageDialog(null,"aula cadastrada", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null,"Erro no cadastro de aula", "Erro", JOptionPane.ERROR_MESSAGE);
            erro = false;
        }
    }

    /**
     * imageparam args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroAulaPanel;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JComboBox<String> categoriaCBox;
    private javax.swing.JLabel caulaLabel;
    private javax.swing.JTextField clienteIdTField;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JFormattedTextField dataTField;
    private javax.swing.JLabel header;
    private javax.swing.JComboBox<String> horarioInicioCBox;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JComboBox<String> horarioTerminoCBox;
    private javax.swing.JLabel horarioTerminoLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel image;
    private javax.swing.JComboBox<String> professorCBox;
    private javax.swing.JLabel professorLabel;
    // End of variables declaration//GEN-END:variables
}
