/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.controlador.cadastro.CadastroFuncionario;
import bodyfitness.dao.CargoDAO;
import bodyfitness.pessoas.caracteristicas.Cargo;
import bodyfitness.pessoas.caracteristicas.Endereco;
import bodyfitness.pessoas.caracteristicas.Permissao;
import bodyfitness.pessoas.caracteristicas.Turno;
import bodyfitness.pessoas.funcionarios.Funcionario;
import bodyfitness.pessoas.generico.TipoDePessoa;
import bodyfitness.util.UtilBodyfitness;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a1509950
 */
public class CadastroFuncionário extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionário
     */
    public CadastroFuncionário() {
        initComponents();
        CargoDAO dao = new CargoDAO();
        List<Cargo> cargos = new ArrayList<>();
        cargos = dao.consultarTodos();
        for(Cargo c : cargos) {
            this.cargoCBox.addItem(c.getFuncao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroFuncPanel = new javax.swing.JPanel();
        dataNascimentoLabel = new javax.swing.JLabel();
        salarioLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        confirmacaoLabel = new javax.swing.JLabel();
        turnoLabel = new javax.swing.JLabel();
        ruaLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        cidadeLabel = new javax.swing.JLabel();
        cidadeTField = new javax.swing.JTextField();
        numeroTField = new javax.swing.JTextField();
        bairroTField = new javax.swing.JTextField();
        ruaTField = new javax.swing.JTextField();
        datanascTField = new javax.swing.JTextField();
        senhaTField = new javax.swing.JPasswordField();
        confsenhaTField = new javax.swing.JPasswordField();
        salarioTField = new javax.swing.JTextField();
        nomeTField = new javax.swing.JTextField();
        estadoCBox = new javax.swing.JComboBox<>();
        turnoCBox = new javax.swing.JComboBox<>();
        estadoLabel = new javax.swing.JLabel();
        cadastroButton = new javax.swing.JButton();
        head = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        cargoCBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        usuarioTField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        CadastroFuncPanel.setLayout(null);

        dataNascimentoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        dataNascimentoLabel.setForeground(new java.awt.Color(254, 254, 254));
        dataNascimentoLabel.setText("Data de Nascimento :");
        dataNascimentoLabel.setToolTipText("");
        CadastroFuncPanel.add(dataNascimentoLabel);
        dataNascimentoLabel.setBounds(450, 110, 240, 50);

        salarioLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        salarioLabel.setForeground(new java.awt.Color(254, 254, 254));
        salarioLabel.setText("Salário :");
        CadastroFuncPanel.add(salarioLabel);
        salarioLabel.setBounds(450, 190, 120, 50);

        senhaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(254, 254, 254));
        senhaLabel.setText("Senha :");
        CadastroFuncPanel.add(senhaLabel);
        senhaLabel.setBounds(450, 340, 80, 50);

        nomeLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(254, 254, 254));
        nomeLabel.setText("Nome :");
        CadastroFuncPanel.add(nomeLabel);
        nomeLabel.setBounds(50, 110, 80, 50);

        confirmacaoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        confirmacaoLabel.setForeground(new java.awt.Color(254, 254, 254));
        confirmacaoLabel.setText("Confirmar Senha :");
        CadastroFuncPanel.add(confirmacaoLabel);
        confirmacaoLabel.setBounds(450, 400, 200, 50);

        turnoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        turnoLabel.setForeground(new java.awt.Color(254, 254, 254));
        turnoLabel.setText("Turno :");
        CadastroFuncPanel.add(turnoLabel);
        turnoLabel.setBounds(450, 550, 80, 50);

        ruaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ruaLabel.setForeground(new java.awt.Color(254, 254, 254));
        ruaLabel.setText("Rua :");
        ruaLabel.setToolTipText("");
        CadastroFuncPanel.add(ruaLabel);
        ruaLabel.setBounds(50, 270, 80, 50);

        bairroLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        bairroLabel.setForeground(new java.awt.Color(254, 254, 254));
        bairroLabel.setText("Bairro :");
        CadastroFuncPanel.add(bairroLabel);
        bairroLabel.setBounds(50, 190, 80, 50);

        numeroLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        numeroLabel.setForeground(new java.awt.Color(254, 254, 254));
        numeroLabel.setText("Número :");
        CadastroFuncPanel.add(numeroLabel);
        numeroLabel.setBounds(50, 350, 120, 50);

        cidadeLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        cidadeLabel.setForeground(new java.awt.Color(254, 254, 254));
        cidadeLabel.setText("Cidade :");
        CadastroFuncPanel.add(cidadeLabel);
        cidadeLabel.setBounds(50, 430, 120, 50);
        CadastroFuncPanel.add(cidadeTField);
        cidadeTField.setBounds(180, 430, 210, 50);
        CadastroFuncPanel.add(numeroTField);
        numeroTField.setBounds(180, 350, 210, 50);
        CadastroFuncPanel.add(bairroTField);
        bairroTField.setBounds(140, 190, 250, 50);
        CadastroFuncPanel.add(ruaTField);
        ruaTField.setBounds(140, 270, 250, 50);
        CadastroFuncPanel.add(datanascTField);
        datanascTField.setBounds(700, 110, 230, 50);
        CadastroFuncPanel.add(senhaTField);
        senhaTField.setBounds(580, 340, 350, 50);
        CadastroFuncPanel.add(confsenhaTField);
        confsenhaTField.setBounds(660, 400, 270, 50);
        CadastroFuncPanel.add(salarioTField);
        salarioTField.setBounds(580, 190, 350, 50);

        nomeTField.setVerifyInputWhenFocusTarget(false);
        nomeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFieldActionPerformed(evt);
            }
        });
        CadastroFuncPanel.add(nomeTField);
        nomeTField.setBounds(140, 110, 250, 50);

        estadoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC ", "AL", "AP ", "AM", "BA", "CE ", "DF ", "ES ", "GO  ", "MA  ", "MT", "MS ", "MG ", "PA", "PB ", "PR ", "PE ", "PI ", "RJ ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        CadastroFuncPanel.add(estadoCBox);
        estadoCBox.setBounds(180, 510, 210, 50);

        turnoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "noturno", "diurno", "vespertino" }));
        CadastroFuncPanel.add(turnoCBox);
        turnoCBox.setBounds(540, 550, 150, 50);

        estadoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(254, 254, 254));
        estadoLabel.setText("Estado :");
        CadastroFuncPanel.add(estadoLabel);
        estadoLabel.setBounds(50, 510, 120, 50);

        cadastroButton.setText("Cadastrar");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        CadastroFuncPanel.add(cadastroButton);
        cadastroButton.setBounds(750, 550, 160, 50);

        head.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        head.setForeground(new java.awt.Color(254, 254, 254));
        head.setText("Cadastro de Funcionário");
        CadastroFuncPanel.add(head);
        head.setBounds(50, 20, 700, 60);

        cargoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        cargoLabel.setForeground(new java.awt.Color(254, 254, 254));
        cargoLabel.setText("Cargo :");
        CadastroFuncPanel.add(cargoLabel);
        cargoLabel.setBounds(450, 460, 80, 50);

        cargoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CadastroFuncPanel.add(cargoCBox);
        cargoCBox.setBounds(540, 460, 390, 50);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Usuário");
        CadastroFuncPanel.add(jLabel1);
        jLabel1.setBounds(450, 290, 110, 29);
        CadastroFuncPanel.add(usuarioTField);
        usuarioTField.setBounds(580, 277, 350, 40);

        image.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        image.setForeground(new java.awt.Color(254, 254, 254));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("Estado :");
        CadastroFuncPanel.add(image);
        image.setBounds(-190, -140, 1210, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroFuncPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroFuncPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTFieldActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario cadastro = new CadastroFuncionario();
        
        Funcionario funcionario = new Funcionario();
        Endereco endereco = new Endereco();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataDeNascimento = new Date();
        try {
             dataDeNascimento = formato.parse(this.datanascTField.getText());
        } catch (ParseException ex) {
            Logger.getLogger(CadastroFuncionário.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(nomeTField.getText().equals("") || cargoCBox.getSelectedItem().toString().equals("") || usuarioTField.getText().isEmpty() || salarioTField.getText().isEmpty() || cidadeTField.getText().isEmpty() || confsenhaTField.getText().isEmpty() || senhaTField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "existem campos vazios","Erro", JOptionPane.ERROR_MESSAGE);
        }
        else if(!senhaTField.getText().equals(confsenhaTField.getText())) {
            JOptionPane.showMessageDialog(null,"senha não confere", "Erro", JOptionPane.ERROR_MESSAGE);
            senhaTField.setText("");
            confsenhaTField.setText("");
        }
        else if(!this.datanascTField.getText().matches("^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$")) {
                    JOptionPane.showMessageDialog(null, "Erro no formato da data", "Erro", JOptionPane.ERROR_MESSAGE);
                    this.datanascTField.setText("");
                    this.datanascTField.setText("");
        }
        else if(!this.numeroTField.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Erro no campo de número", "Erro", JOptionPane.ERROR_MESSAGE);
            this.numeroTField.setText("");
        }
        else if(!this.salarioTField.getText().matches("[0-9]+\\.[0-9][0-9]")) {
            JOptionPane.showMessageDialog(null, "Erro no campo de salario", "Erro", JOptionPane.ERROR_MESSAGE);
            this.salarioTField.setText("");
        }
        else if(UtilBodyfitness.getDiferencaEmAnos(dataDeNascimento) < new Long(16)) {
            JOptionPane.showMessageDialog(null,"não é permitido funcionário abaixo de 16 anos!", "Erro", JOptionPane.ERROR_MESSAGE);
            this.datanascTField.setText("");
        }
        else {
            bodyfitness.controlador.cadastro.CadastroCargo pcargo = new bodyfitness.controlador.cadastro.CadastroCargo();
            
            CadastroFuncionario cfunc = new CadastroFuncionario();
            Double salario = Double.valueOf(this.salarioTField.getText());
            Endereco end = new Endereco();
            end.setRua(this.ruaTField.getText());
            end.setBairro(this.bairroTField.getText());
            end.setNumero(this.numeroTField.getText());
            end.setCidade(this.cidadeTField.getText());
            end.setEstado(this.estadoCBox.getSelectedItem().toString());
            Turno t;
            if(this.turnoCBox.getSelectedItem().toString().toLowerCase().equals("vespertino")) {
                t = Turno.VESPERTINO;
            }
            else if(this.turnoCBox.getSelectedItem().toString().toLowerCase().equals("matutino")) {
                t = Turno.MATUTINO;
            }
            else {
                t = Turno.NOTURNO;
            }
            try {
                cfunc.cadastrarFuncionario(this.nomeTField.getText(),pcargo.dao.consultarPorFuncao(this.cargoCBox.getSelectedItem().toString()) , t, salario, end, this.datanascTField.getText(), this.usuarioTField.getText(), this.senhaTField.getText());
                JOptionPane.showMessageDialog(null, "Funcionário cadastrado com Sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
                this.bairroTField.setText("");
                this.cidadeTField.setText("");
                this.confsenhaTField.setText("");
                this.senhaTField.setText("");
                this.datanascTField.setText("");
                this.numeroTField.setText("");
                this.nomeTField.setText("");
                this.ruaTField.setText("");
                this.usuarioTField.setText("");
                this.salarioTField.setText("");
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(CadastroFuncionário.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(CadastroFuncionário.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(CadastroFuncionário.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_cadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroFuncPanel;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTField;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JComboBox<String> cargoCBox;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JTextField cidadeTField;
    private javax.swing.JLabel confirmacaoLabel;
    private javax.swing.JPasswordField confsenhaTField;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JTextField datanascTField;
    private javax.swing.JComboBox<String> estadoCBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel head;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTField;
    private javax.swing.JLabel ruaLabel;
    private javax.swing.JTextField ruaTField;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JTextField salarioTField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaTField;
    private javax.swing.JComboBox<String> turnoCBox;
    private javax.swing.JLabel turnoLabel;
    private javax.swing.JTextField usuarioTField;
    // End of variables declaration//GEN-END:variables
}
