/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.aula.Aula;
import bodyfitness.aula.CategoriaDeAula;
import bodyfitness.dao.AulaDAO;
import bodyfitness.dao.CategoriaDeAulaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class CadastroCategoriaAula extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCategoriaAula
     */
    public CadastroCategoriaAula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroCAulaPanel = new javax.swing.JPanel();
        nomeCAulaTField = new javax.swing.JTextField();
        aulaButton = new javax.swing.JButton();
        ccLabel = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        CadastroCAulaPanel.setLayout(null);

        nomeCAulaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCAulaTFieldActionPerformed(evt);
            }
        });
        CadastroCAulaPanel.add(nomeCAulaTField);
        nomeCAulaTField.setBounds(100, 270, 310, 50);

        aulaButton.setText("Criar Categoria");
        aulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulaButtonActionPerformed(evt);
            }
        });
        CadastroCAulaPanel.add(aulaButton);
        aulaButton.setBounds(150, 350, 210, 40);

        ccLabel.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        ccLabel.setForeground(new java.awt.Color(254, 254, 254));
        ccLabel.setText("Criação de Categoria de Aula");
        CadastroCAulaPanel.add(ccLabel);
        ccLabel.setBounds(60, 20, 620, 110);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        CadastroCAulaPanel.add(image);
        image.setBounds(-690, -170, 2030, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroCAulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroCAulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCAulaTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCAulaTFieldActionPerformed
        // TODO add your handling code here:

        String field = nomeCAulaTField.getText();
        System.out.println(field);
    }//GEN-LAST:event_nomeCAulaTFieldActionPerformed

    private void aulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulaButtonActionPerformed
        // TODO add your handling code here:
        if(this.nomeCAulaTField.getText().matches("^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$")) {
            CategoriaDeAula cat = new CategoriaDeAula();
            cat.setCategoria(this.nomeCAulaTField.getText());
            CategoriaDeAulaDAO dao = new CategoriaDeAulaDAO();
            dao.persist(cat);
            JOptionPane.showMessageDialog(null, "categoria de aula salva com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            this.nomeCAulaTField.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Erro no nome da categoria de aula", "Erro", JOptionPane.INFORMATION_MESSAGE);
            this.nomeCAulaTField.setText("");
        }
    }//GEN-LAST:event_aulaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoriaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoriaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoriaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCategoriaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCategoriaAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroCAulaPanel;
    private javax.swing.JButton aulaButton;
    private javax.swing.JLabel ccLabel;
    private javax.swing.JLabel image;
    private javax.swing.JTextField nomeCAulaTField;
    // End of variables declaration//GEN-END:variables
}
