/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class ClienteEditarMembrosSuperiores extends javax.swing.JFrame {

    /**
     * Creates new form ClienteEditarMembrosSuperiores
     */
    public ClienteEditarMembrosSuperiores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliaçãoPanel = new javax.swing.JPanel();
        ombroLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        toraxRelaxadoLabel = new javax.swing.JLabel();
        cinturaLabel = new javax.swing.JLabel();
        pescocoLabel = new javax.swing.JLabel();
        toraxInspiradoLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        ombroTField = new javax.swing.JTextField();
        idTField = new javax.swing.JTextField();
        toraxRelaxadoTField = new javax.swing.JTextField();
        cinturaTField = new javax.swing.JTextField();
        toraxInspiradoTField = new javax.swing.JTextField();
        pescocoTField = new javax.swing.JTextField();
        abdomeLabel = new javax.swing.JLabel();
        quadrilLabel = new javax.swing.JLabel();
        relacaoCinturaXQuadrilLabel = new javax.swing.JLabel();
        abdomeTField = new javax.swing.JTextField();
        quadrilTField = new javax.swing.JTextField();
        relacaoCinturaXQuadrilTField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avaliaçãoPanel.setPreferredSize(new java.awt.Dimension(1000, 650));
        avaliaçãoPanel.setLayout(null);

        ombroLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ombroLabel.setForeground(new java.awt.Color(254, 254, 254));
        ombroLabel.setText("Ombro :");
        avaliaçãoPanel.add(ombroLabel);
        ombroLabel.setBounds(60, 100, 100, 50);

        idLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(254, 254, 254));
        idLabel.setText("ID :");
        avaliaçãoPanel.add(idLabel);
        idLabel.setBounds(70, 200, 50, 50);

        toraxRelaxadoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        toraxRelaxadoLabel.setForeground(new java.awt.Color(254, 254, 254));
        toraxRelaxadoLabel.setText("Torax Relaxado :");
        avaliaçãoPanel.add(toraxRelaxadoLabel);
        toraxRelaxadoLabel.setBounds(60, 300, 180, 50);

        cinturaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        cinturaLabel.setForeground(new java.awt.Color(254, 254, 254));
        cinturaLabel.setText("Cintura :");
        avaliaçãoPanel.add(cinturaLabel);
        cinturaLabel.setBounds(510, 300, 100, 50);

        pescocoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        pescocoLabel.setForeground(new java.awt.Color(254, 254, 254));
        pescocoLabel.setText("Pescoço :");
        avaliaçãoPanel.add(pescocoLabel);
        pescocoLabel.setBounds(500, 100, 110, 50);

        toraxInspiradoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        toraxInspiradoLabel.setForeground(new java.awt.Color(254, 254, 254));
        toraxInspiradoLabel.setText("Torax Inspirado :");
        avaliaçãoPanel.add(toraxInspiradoLabel);
        toraxInspiradoLabel.setBounds(510, 200, 180, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Editar Membros Superiores");
        header.setToolTipText("");
        avaliaçãoPanel.add(header);
        header.setBounds(310, 20, 450, 50);

        editarButton.setText("Editar");
        avaliaçãoPanel.add(editarButton);
        editarButton.setBounds(510, 500, 80, 50);

        ombroTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ombroTFieldActionPerformed(evt);
            }
        });
        avaliaçãoPanel.add(ombroTField);
        ombroTField.setBounds(160, 100, 280, 50);
        avaliaçãoPanel.add(idTField);
        idTField.setBounds(130, 200, 310, 50);
        avaliaçãoPanel.add(toraxRelaxadoTField);
        toraxRelaxadoTField.setBounds(250, 300, 190, 50);
        avaliaçãoPanel.add(cinturaTField);
        cinturaTField.setBounds(610, 300, 330, 50);
        avaliaçãoPanel.add(toraxInspiradoTField);
        toraxInspiradoTField.setBounds(700, 200, 240, 50);
        avaliaçãoPanel.add(pescocoTField);
        pescocoTField.setBounds(610, 100, 330, 50);

        abdomeLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        abdomeLabel.setForeground(new java.awt.Color(254, 254, 254));
        abdomeLabel.setText("Abdome :");
        avaliaçãoPanel.add(abdomeLabel);
        abdomeLabel.setBounds(60, 400, 100, 50);

        quadrilLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        quadrilLabel.setForeground(new java.awt.Color(254, 254, 254));
        quadrilLabel.setText("Quadril :");
        avaliaçãoPanel.add(quadrilLabel);
        quadrilLabel.setBounds(60, 500, 110, 50);

        relacaoCinturaXQuadrilLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        relacaoCinturaXQuadrilLabel.setForeground(new java.awt.Color(254, 254, 254));
        relacaoCinturaXQuadrilLabel.setText("Cintura X Quadril :");
        avaliaçãoPanel.add(relacaoCinturaXQuadrilLabel);
        relacaoCinturaXQuadrilLabel.setBounds(510, 400, 210, 50);
        avaliaçãoPanel.add(abdomeTField);
        abdomeTField.setBounds(170, 400, 270, 50);
        avaliaçãoPanel.add(quadrilTField);
        quadrilTField.setBounds(170, 500, 270, 50);
        avaliaçãoPanel.add(relacaoCinturaXQuadrilTField);
        relacaoCinturaXQuadrilTField.setBounds(720, 400, 220, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("image");
        avaliaçãoPanel.add(image);
        image.setBounds(-110, -50, 1962, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ombroTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ombroTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ombroTFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarMembrosSuperiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarMembrosSuperiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarMembrosSuperiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarMembrosSuperiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEditarMembrosSuperiores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abdomeLabel;
    private javax.swing.JTextField abdomeTField;
    private javax.swing.JPanel avaliaçãoPanel;
    private javax.swing.JLabel cinturaLabel;
    private javax.swing.JTextField cinturaTField;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel ombroLabel;
    private javax.swing.JTextField ombroTField;
    private javax.swing.JLabel pescocoLabel;
    private javax.swing.JTextField pescocoTField;
    private javax.swing.JLabel quadrilLabel;
    private javax.swing.JTextField quadrilTField;
    private javax.swing.JLabel relacaoCinturaXQuadrilLabel;
    private javax.swing.JTextField relacaoCinturaXQuadrilTField;
    private javax.swing.JLabel toraxInspiradoLabel;
    private javax.swing.JTextField toraxInspiradoTField;
    private javax.swing.JLabel toraxRelaxadoLabel;
    private javax.swing.JTextField toraxRelaxadoTField;
    // End of variables declaration//GEN-END:variables
}
