/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class ClienteEditarTreino extends javax.swing.JFrame {

    /**
     * Creates new form ClienteEditarTreino
     */
    public ClienteEditarTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treinoPanel = new javax.swing.JPanel();
        rotuloLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        equipamentoLabel = new javax.swing.JLabel();
        quantidadeDeSeriesLabel = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        rotuloTField = new javax.swing.JTextField();
        idTField = new javax.swing.JTextField();
        coxaEsquerdoTField = new javax.swing.JTextField();
        qtdSériesTField = new javax.swing.JTextField();
        repeticoesLabel = new javax.swing.JLabel();
        repetiçõesTField = new javax.swing.JTextField();
        equipamentoCBox = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        treinoPanel.setPreferredSize(new java.awt.Dimension(1000, 650));
        treinoPanel.setLayout(null);

        rotuloLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        rotuloLabel.setForeground(new java.awt.Color(254, 254, 254));
        rotuloLabel.setText("Rótulo :");
        treinoPanel.add(rotuloLabel);
        rotuloLabel.setBounds(60, 160, 100, 50);

        idLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(254, 254, 254));
        idLabel.setText("ID :");
        treinoPanel.add(idLabel);
        idLabel.setBounds(60, 260, 50, 50);

        equipamentoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        equipamentoLabel.setForeground(new java.awt.Color(254, 254, 254));
        equipamentoLabel.setText("Equipamento :");
        treinoPanel.add(equipamentoLabel);
        equipamentoLabel.setBounds(60, 360, 160, 50);

        quantidadeDeSeriesLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        quantidadeDeSeriesLabel.setForeground(new java.awt.Color(254, 254, 254));
        quantidadeDeSeriesLabel.setText("Qtd. de Séries :");
        treinoPanel.add(quantidadeDeSeriesLabel);
        quantidadeDeSeriesLabel.setBounds(500, 160, 170, 50);

        diaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        diaLabel.setForeground(new java.awt.Color(254, 254, 254));
        diaLabel.setText("Dia :");
        treinoPanel.add(diaLabel);
        diaLabel.setBounds(510, 260, 60, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Editar Treino");
        header.setToolTipText("");
        treinoPanel.add(header);
        header.setBounds(380, 40, 220, 50);

        editarButton.setText("Editar");
        treinoPanel.add(editarButton);
        editarButton.setBounds(500, 490, 80, 50);
        
        deletarButton.setText("Deletar");
        treinoPanel.add(deletarButton);
        deletarButton.setBounds(420, 490, 80, 50);

        rotuloTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotuloTFieldActionPerformed(evt);
            }
        });
        treinoPanel.add(rotuloTField);
        rotuloTField.setBounds(150, 160, 290, 50);
        treinoPanel.add(idTField);
        idTField.setBounds(130, 260, 310, 50);
        treinoPanel.add(coxaEsquerdoTField);
        coxaEsquerdoTField.setBounds(580, 260, 360, 50);
        treinoPanel.add(qtdSériesTField);
        qtdSériesTField.setBounds(680, 160, 260, 50);

        repeticoesLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        repeticoesLabel.setForeground(new java.awt.Color(254, 254, 254));
        repeticoesLabel.setText("Repetições :");
        treinoPanel.add(repeticoesLabel);
        repeticoesLabel.setBounds(510, 360, 140, 50);
        treinoPanel.add(repetiçõesTField);
        repetiçõesTField.setBounds(650, 360, 290, 50);

        treinoPanel.add(equipamentoCBox);
        equipamentoCBox.setBounds(230, 360, 210, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("image");
        treinoPanel.add(image);
        image.setBounds(-110, -50, 1962, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(treinoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(treinoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotuloTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotuloTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotuloTFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEditarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEditarTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coxaEsquerdoTField;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton deletarButton;
    private javax.swing.JComboBox<String> equipamentoCBox;
    private javax.swing.JLabel equipamentoLabel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel image;
    private javax.swing.JTextField qtdSériesTField;
    private javax.swing.JLabel quantidadeDeSeriesLabel;
    private javax.swing.JLabel repeticoesLabel;
    private javax.swing.JTextField repetiçõesTField;
    private javax.swing.JLabel rotuloLabel;
    private javax.swing.JTextField rotuloTField;
    private javax.swing.JPanel treinoPanel;
    // End of variables declaration//GEN-END:variables
}
