/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.dao.ClienteDAO;
import bodyfitness.dao.EquipamentoDAO;
import bodyfitness.equipamentos.Equipamento;
import bodyfitness.pessoas.cliente.Cliente;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author a1509950
 */
public class confirmaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form confirmaManutenção
     */
    public confirmaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        buscaLabel = new javax.swing.JLabel();
        critérioLabel = new javax.swing.JLabel();
        buscaTField = new javax.swing.JTextField();
        critérioCBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        resultadoCBox = new javax.swing.JComboBox<>();
        resultadoLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultaPanel.setLayout(null);

        headerLabel.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(254, 254, 254));
        headerLabel.setText("Consulta de Pagamento");
        consultaPanel.add(headerLabel);
        headerLabel.setBounds(290, 20, 460, 50);

        buscaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        buscaLabel.setForeground(new java.awt.Color(254, 254, 254));
        buscaLabel.setText("Busca :");
        consultaPanel.add(buscaLabel);
        buscaLabel.setBounds(70, 230, 80, 50);

        critérioLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        critérioLabel.setForeground(new java.awt.Color(254, 254, 254));
        critérioLabel.setText("Critério :");
        consultaPanel.add(critérioLabel);
        critérioLabel.setBounds(50, 130, 100, 50);

        buscaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaTFieldActionPerformed(evt);
            }
        });
        consultaPanel.add(buscaTField);
        buscaTField.setBounds(160, 230, 780, 50);

        critérioCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nome", "id" }));
        consultaPanel.add(critérioCBox);
        critérioCBox.setBounds(160, 130, 600, 50);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        consultaPanel.add(buscarButton);
        buscarButton.setBounds(800, 130, 140, 50);

        consultaPanel.add(resultadoCBox);
        resultadoCBox.setBounds(160, 340, 600, 50);

        resultadoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        resultadoLabel.setForeground(new java.awt.Color(254, 254, 254));
        resultadoLabel.setText("Pagamento");
        consultaPanel.add(resultadoLabel);
        resultadoLabel.setBounds(10, 340, 140, 50);

        okButton.setText("Confirma");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        consultaPanel.add(okButton);
        okButton.setBounds(800, 340, 140, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        consultaPanel.add(image);
        image.setBounds(-50, -50, 1968, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaTFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        if(this.critérioCBox.getSelectedItem().toString().equals("nome")) {
            this.resultadoCBox.removeAllItems();
            ClienteDAO dao = new ClienteDAO();
            List<Cliente> clientes = dao.consultarPorNome(this.buscaTField.getText());
            for(Cliente c : clientes) {
                this.resultadoCBox.addItem(c.getId().toString() + " - " + c.getNome());
            }
        }
        else {
            this.resultadoCBox.removeAllItems();
            ClienteDAO dao = new ClienteDAO();
            Cliente cliente = dao.consultarPorId(Long.valueOf(this.buscaTField.getText()));
            this.resultadoCBox.addItem(cliente.getId() + " - " + cliente.getNome());
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.consultarPorId(Long.valueOf(this.resultadoCBox.getSelectedItem().toString().split(" - ")[0]));
        cliente.setPago(true);
        Calendar c = Calendar.getInstance();
        c.add(Calendar.MONTH, 1);
        cliente.setDataDePagamento(c.getTime());
        cliente.setSituacaoFinanceira();
        dao.persist(cliente);
        JOptionPane.showMessageDialog(null,"Pagamento mensal confirmado", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JTextField buscaTField;
    private javax.swing.JButton buscarButton;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JComboBox<String> critérioCBox;
    private javax.swing.JLabel critérioLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel image;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> resultadoCBox;
    private javax.swing.JLabel resultadoLabel;
    // End of variables declaration//GEN-END:variables
}
