/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.aula.Aula;
import bodyfitness.dao.AulaDAO;
import bodyfitness.dao.CategoriaDeAulaDAO;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class ConsultaAula extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaAula
     */
    public ConsultaAula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaAulaPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        buscaLabel = new javax.swing.JLabel();
        buscaButton = new javax.swing.JButton();
        buscaTField = new javax.swing.JTextField();
        tabelaSPanel = new javax.swing.JScrollPane();
        buscaTable = new javax.swing.JTable();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultaAulaPanel.setLayout(null);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Consulta Aulas");
        consultaAulaPanel.add(header);
        header.setBounds(370, 30, 250, 50);

        buscaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        buscaLabel.setForeground(new java.awt.Color(254, 254, 254));
        buscaLabel.setText("Busca :");
        consultaAulaPanel.add(buscaLabel);
        buscaLabel.setBounds(20, 120, 90, 50);

        buscaButton.setText("Buscar");
        consultaAulaPanel.add(buscaButton);
        buscaButton.setBounds(800, 120, 180, 50);
        consultaAulaPanel.add(buscaTField);
        buscaTField.setBounds(120, 120, 670, 50);

        buscaTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Professor", "Horário Início", "Horário Término", "Data"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        buscaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaButtonActionPerformed(evt);
            }
        });
        tabelaSPanel.setViewportView(buscaTable);

        consultaAulaPanel.add(tabelaSPanel);
        tabelaSPanel.setBounds(20, 190, 960, 430);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        consultaAulaPanel.add(image);
        image.setBounds(-160, -230, 2970, 1450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(consultaAulaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(consultaAulaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void buscaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        AulaDAO dao = new AulaDAO();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        CategoriaDeAulaDAO cdao = new CategoriaDeAulaDAO();
        List<Aula> aulas = dao.consultarPorCategoriaDeAula(this.buscaTField.getText());
        String[][] resultado = new String[aulas.size()][4];
        int i = 0;
        for (Aula a : aulas) {
            resultado[i] = new String[]{a.getProfessor().getNome(), a.getHoraDeInicio(), a.getHoraDeTermino(), formato.format(a.getDia())};
            i++;
        }
        buscaTable.setModel(new javax.swing.table.DefaultTableModel(
                resultado,
                new String[]{
                    "Professor", "Horário Início", "Horário Término", "Data"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaButton;
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JTextField buscaTField;
    private javax.swing.JTable buscaTable;
    private javax.swing.JPanel consultaAulaPanel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel image;
    private javax.swing.JScrollPane tabelaSPanel;
    // End of variables declaration//GEN-END:variables
}
