/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.relatorios.Relatorio;
import javax.swing.JOptionPane;

/**
 *
 * @author a1509950
 */
public class GerarRelatório extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatório
     */
    public GerarRelatório() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gerarRelatório = new javax.swing.JPanel();
        categorialLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        gerarRelatórioButton = new javax.swing.JButton();
        categoriaCBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        gerarRelatório.setLayout(null);

        categorialLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        categorialLabel.setForeground(new java.awt.Color(254, 254, 254));
        categorialLabel.setText("Categoria :");
        gerarRelatório.add(categorialLabel);
        categorialLabel.setBounds(220, 300, 130, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Geração de Relatórios");
        gerarRelatório.add(header);
        header.setBounds(340, 120, 360, 50);

        gerarRelatórioButton.setText("Gerar Relatório");
        gerarRelatórioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatórioButtonActionPerformed(evt);
            }
        });
        gerarRelatório.add(gerarRelatórioButton);
        gerarRelatórioButton.setBounds(440, 460, 130, 50);

        categoriaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inadimplente", "adimplente", "treino por id do cliente", "avaliação por id do cliente", "maquina sem manutenção" }));
        gerarRelatório.add(categoriaCBox);
        categoriaCBox.setBounds(350, 300, 440, 50);

        jTextField1.setText("digite o id...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gerarRelatório.add(jTextField1);
        jTextField1.setBounds(350, 380, 260, 40);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        gerarRelatório.add(image);
        image.setBounds(-120, -50, 1971, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarRelatórioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatórioButtonActionPerformed
        // TODO add your handling code here:
        if (this.categoriaCBox.getSelectedItem().toString().equals("inadimplente")) {
            Relatorio r = new Relatorio();
            r.GeraRelatorioInadimplente("");
            JOptionPane.showMessageDialog(null, "relatório de inadimplentes gerado com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        } else if (this.categoriaCBox.getSelectedItem().toString().equals("adimplente")) {
            Relatorio r = new Relatorio();
            r.GeraRelatorioAdimplente("");
            JOptionPane.showMessageDialog(null, "relatório de adimplentes gerado com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        } else if (this.categoriaCBox.getSelectedItem().toString().equals("maquina sem manutenção")) {
            Relatorio r = new Relatorio();
            r.GeraRelatorioMaquinaSManutencao("");
            JOptionPane.showMessageDialog(null, "relatório de maquina gerado com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);

        } else if (this.categoriaCBox.getSelectedItem().toString().equals("treino por id do cliente")) {
            Relatorio r = new Relatorio();
            r.GeraRelatorioTreino("", Long.valueOf(this.jTextField1.getText()));
            JOptionPane.showMessageDialog(null, "relatório de treino gerado com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        } else if (this.categoriaCBox.getSelectedItem().toString().equals("avaliação por id do cliente")) {
            Relatorio r = new Relatorio();
            r.GeraRelatorioCondFisico("", Long.valueOf(this.jTextField1.getText()));
            JOptionPane.showMessageDialog(null, "relatório de avaliação gerado com sucesso", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_gerarRelatórioButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatório().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriaCBox;
    private javax.swing.JLabel categorialLabel;
    private javax.swing.JPanel gerarRelatório;
    private javax.swing.JButton gerarRelatórioButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel image;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
