/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

/**
 *
 * @author a1509950
 */
public class GerarRelatório extends javax.swing.JFrame {

    /**
     * Creates new form GerarRelatório
     */
    public GerarRelatório() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gerarRelatório = new javax.swing.JPanel();
        categorialLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        gerarRelatórioButton = new javax.swing.JButton();
        categoriaCBox = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        gerarRelatório.setLayout(null);

        categorialLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        categorialLabel.setForeground(new java.awt.Color(254, 254, 254));
        categorialLabel.setText("Categoria :");
        gerarRelatório.add(categorialLabel);
        categorialLabel.setBounds(220, 300, 130, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Geração de Relatórios");
        gerarRelatório.add(header);
        header.setBounds(340, 120, 360, 50);

        gerarRelatórioButton.setText("Gerar Relatório");
        gerarRelatório.add(gerarRelatórioButton);
        gerarRelatórioButton.setBounds(440, 460, 130, 50);

        categoriaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inadimplente", "adimplente", "treino por id do cliente", "avaliação por id do cliente", "maquina sem manutenção" }));
        gerarRelatório.add(categoriaCBox);
        categoriaCBox.setBounds(350, 300, 440, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        gerarRelatório.add(image);
        image.setBounds(-10, -20, 1969, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatório.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatório().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriaCBox;
    private javax.swing.JLabel categorialLabel;
    private javax.swing.JPanel gerarRelatório;
    private javax.swing.JButton gerarRelatórioButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel image;
    // End of variables declaration//GEN-END:variables
}
