/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.dao.AdministradorDAO;
import bodyfitness.dao.FuncionarioDAO;
import bodyfitness.pessoas.funcionarios.Administrador;
import java.security.MessageDigest;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class LoginSistema extends javax.swing.JFrame {

    /**
     * Creates new form LoginSistema
     */
    public LoginSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        senhaTField = new javax.swing.JPasswordField();
        usuarioTField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel.setLayout(null);

        headerLabel.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(254, 254, 254));
        headerLabel.setText("Login");
        loginPanel.add(headerLabel);
        headerLabel.setBounds(320, 110, 90, 50);

        loginLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(254, 254, 254));
        loginLabel.setText("Usuário :");
        loginPanel.add(loginLabel);
        loginLabel.setBounds(110, 230, 100, 50);

        senhaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(254, 254, 254));
        senhaLabel.setText("Senha :");
        loginPanel.add(senhaLabel);
        senhaLabel.setBounds(130, 290, 80, 50);
        loginPanel.add(senhaTField);
        senhaTField.setBounds(220, 290, 290, 50);
        loginPanel.add(usuarioTField);
        usuarioTField.setBounds(220, 230, 290, 50);

        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(320, 380, 80, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("jLabel1");
        loginPanel.add(image);
        image.setBounds(-650, -80, 1969, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        AdministradorDAO adao = new AdministradorDAO();
        FuncionarioDAO fdao = new FuncionarioDAO();
        boolean verificaADM = false;
        try {
            Administrador adm = adao.consultarPorUsuario(this.usuarioTField.getText());
            String senha = this.senhaTField.getText();
            MessageDigest algorithm = MessageDigest.getInstance("MD5");
            byte messageDigest[] = algorithm.digest(senha.getBytes("UTF-8"));

            StringBuilder hexString = new StringBuilder();
            for (byte b : messageDigest) {
                hexString.append(String.format("%02X", 0xFF & b));
            }
            String senhaCriptografada = hexString.toString();
            if (senhaCriptografada.equals(adm.getSenha())) {
                verificaADM = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no login, acesso comum", "Erro", JOptionPane.INFORMATION_MESSAGE);

        } finally {
            this.setVisible(false);
            
            if(verificaADM == false) {
                JOptionPane.showMessageDialog(null, "Erro no login, acesso comum", "Erro", JOptionPane.INFORMATION_MESSAGE);

            }
            MenuPrincipal menu = new MenuPrincipal(verificaADM);

            menu.setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel image;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaTField;
    private javax.swing.JTextField usuarioTField;
    // End of variables declaration//GEN-END:variables
}
