/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.dao.ClienteDAO;
import bodyfitness.pessoas.cliente.Cliente;
import bodyfitness.pessoas.cliente.caracteristicas.corporal.MembrosInferiores;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class PainelClienteEditarMembrosInferiores extends javax.swing.JFrame {

    /**
     * Creates new form PainelClienteEditarMembrosInferiores
     */
    private Long id;
    private boolean alterou;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public PainelClienteEditarMembrosInferiores(Long id) {
        initComponents();
        this.id = id;
        this.idTField.setEditable(false);
        this.idTField.setText(id.toString());
        this.alterou = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliaçãoPanel = new javax.swing.JPanel();
        anteBracoDireitoLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        toraxRelaxadoLabel = new javax.swing.JLabel();
        bracoRelaxadoEsquerdoLabel = new javax.swing.JLabel();
        coxaEsquerdoLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        anteBracoDireitoTField = new javax.swing.JTextField();
        idTField = new javax.swing.JTextField();
        toraxRelaxadoTField = new javax.swing.JTextField();
        coxaEsquerdoTField = new javax.swing.JTextField();
        bracoRelaxadoEsquerdoTField = new javax.swing.JTextField();
        bracoContraidoDireitoLabel = new javax.swing.JLabel();
        panturrilhaDireitoLabel = new javax.swing.JLabel();
        bracoContraidoDireitoTField = new javax.swing.JTextField();
        panturrilhaDireitoTField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avaliaçãoPanel.setPreferredSize(new java.awt.Dimension(1000, 650));
        avaliaçãoPanel.setLayout(null);

        anteBracoDireitoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        anteBracoDireitoLabel.setForeground(new java.awt.Color(254, 254, 254));
        anteBracoDireitoLabel.setText("Ante B. Direito :");
        avaliaçãoPanel.add(anteBracoDireitoLabel);
        anteBracoDireitoLabel.setBounds(60, 160, 180, 50);

        idLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(254, 254, 254));
        idLabel.setText("ID :");
        avaliaçãoPanel.add(idLabel);
        idLabel.setBounds(70, 260, 50, 50);

        toraxRelaxadoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        toraxRelaxadoLabel.setForeground(new java.awt.Color(254, 254, 254));
        toraxRelaxadoLabel.setText("Braço R. Direito :");
        avaliaçãoPanel.add(toraxRelaxadoLabel);
        toraxRelaxadoLabel.setBounds(60, 360, 180, 50);

        bracoRelaxadoEsquerdoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        bracoRelaxadoEsquerdoLabel.setForeground(new java.awt.Color(254, 254, 254));
        bracoRelaxadoEsquerdoLabel.setText("Braço R. Esquerdo :");
        avaliaçãoPanel.add(bracoRelaxadoEsquerdoLabel);
        bracoRelaxadoEsquerdoLabel.setBounds(500, 160, 210, 50);

        coxaEsquerdoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        coxaEsquerdoLabel.setForeground(new java.awt.Color(254, 254, 254));
        coxaEsquerdoLabel.setText("Coxa Esquerda :");
        avaliaçãoPanel.add(coxaEsquerdoLabel);
        coxaEsquerdoLabel.setBounds(510, 260, 180, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Editar Membros Inferiores");
        header.setToolTipText("");
        avaliaçãoPanel.add(header);
        header.setBounds(290, 40, 450, 50);

        editarButton.setText("Editar");
        avaliaçãoPanel.add(editarButton);
        editarButton.setBounds(510, 460, 80, 50);

        anteBracoDireitoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteBracoDireitoTFieldActionPerformed(evt);
            }
        });

        editarButton.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(ActionEvent e) {
                editarButtonTFieldActionPerformed(e);
            }
        });
        avaliaçãoPanel.add(anteBracoDireitoTField);
        anteBracoDireitoTField.setBounds(240, 160, 200, 50);
        avaliaçãoPanel.add(idTField);
        idTField.setBounds(130, 260, 310, 50);
        avaliaçãoPanel.add(toraxRelaxadoTField);
        toraxRelaxadoTField.setBounds(250, 360, 190, 50);
        avaliaçãoPanel.add(coxaEsquerdoTField);
        coxaEsquerdoTField.setBounds(700, 260, 240, 50);
        avaliaçãoPanel.add(bracoRelaxadoEsquerdoTField);
        bracoRelaxadoEsquerdoTField.setBounds(720, 160, 220, 50);

        bracoContraidoDireitoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        bracoContraidoDireitoLabel.setForeground(new java.awt.Color(254, 254, 254));
        bracoContraidoDireitoLabel.setText("Braço C. Direito :");
        avaliaçãoPanel.add(bracoContraidoDireitoLabel);
        bracoContraidoDireitoLabel.setBounds(510, 360, 190, 50);

        panturrilhaDireitoLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        panturrilhaDireitoLabel.setForeground(new java.awt.Color(254, 254, 254));
        panturrilhaDireitoLabel.setText("Panturrilha Direita :");
        avaliaçãoPanel.add(panturrilhaDireitoLabel);
        panturrilhaDireitoLabel.setBounds(50, 460, 220, 50);
        avaliaçãoPanel.add(bracoContraidoDireitoTField);
        bracoContraidoDireitoTField.setBounds(700, 360, 240, 50);
        avaliaçãoPanel.add(panturrilhaDireitoTField);
        panturrilhaDireitoTField.setBounds(270, 460, 170, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("image");
        avaliaçãoPanel.add(image);
        image.setBounds(-110, -50, 1962, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteBracoDireitoTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteBracoDireitoTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anteBracoDireitoTFieldActionPerformed

    private void editarButtonTFieldActionPerformed(java.awt.event.ActionEvent evt) {
        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.consultarPorId(this.getId());
        MembrosInferiores minf = new MembrosInferiores();
        minf = cliente.getCondicionamentoFisico().getMembrosInferiores();
        if (this.anteBracoDireitoTField.getText().matches("[0-9]*\\.[0-9]*")) {
            this.alterou = true;
            minf.setAnteBracoDireito(Double.valueOf(this.anteBracoDireitoTField.getText()));
            JOptionPane.showMessageDialog(null, "antebraço alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if (this.bracoContraidoDireitoTField.getText().matches("[0-9]*\\.[0-9]*")) {
            this.alterou = true;
            minf.setBracoContraidoDireito(Double.valueOf(this.bracoContraidoDireitoTField.getText()));
            JOptionPane.showMessageDialog(null, "braço direito contráido alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if (this.bracoRelaxadoEsquerdoTField.getText().matches("[0-9]*\\.[0-9]*")) {
            this.alterou = true;
            minf.setBracoRelaxadoEsquerdo(Double.valueOf(this.bracoRelaxadoEsquerdoTField.getText()));
            JOptionPane.showMessageDialog(null, "braço esquerdo relaxado alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }

        if (this.coxaEsquerdoTField.getText().matches("[0-9]*\\.[0-9]*")) {
            this.alterou = true;
            minf.setCoxaEsquerdo(Double.valueOf(this.coxaEsquerdoTField.getText()));
            JOptionPane.showMessageDialog(null, "coxa esquerda alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if (this.panturrilhaDireitoTField.getText().matches("[0-9]*\\.[0-9]*")) {
            this.alterou = true;
            minf.setPanturrilhaDireito(Double.valueOf(this.panturrilhaDireitoTField.getText()));
            JOptionPane.showMessageDialog(null, "panturrilha direita contráido alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if (this.alterou == true) {
            cliente.getCondicionamentoFisico().setMembrosInferiores(minf);
            dao.persist(cliente);

            JOptionPane.showMessageDialog(null, "membros inferiores atualizados", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        else  {
            JOptionPane.showMessageDialog(null,"Sem alterações realizadas", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarMembrosInferiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarMembrosInferiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarMembrosInferiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarMembrosInferiores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PainelClienteEditarMembrosInferiores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anteBracoDireitoLabel;
    private javax.swing.JTextField anteBracoDireitoTField;
    private javax.swing.JPanel avaliaçãoPanel;
    private javax.swing.JLabel bracoContraidoDireitoLabel;
    private javax.swing.JTextField bracoContraidoDireitoTField;
    private javax.swing.JLabel bracoRelaxadoEsquerdoLabel;
    private javax.swing.JTextField bracoRelaxadoEsquerdoTField;
    private javax.swing.JLabel coxaEsquerdoLabel;
    private javax.swing.JTextField coxaEsquerdoTField;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel panturrilhaDireitoLabel;
    private javax.swing.JTextField panturrilhaDireitoTField;
    private javax.swing.JLabel toraxRelaxadoLabel;
    private javax.swing.JTextField toraxRelaxadoTField;
    // End of variables declaration//GEN-END:variables
}
