/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodyfitness.quadros.paineis;

import bodyfitness.dao.ClienteDAO;
import bodyfitness.pessoas.cliente.Cliente;
import bodyfitness.pessoas.cliente.caracteristicas.corporal.CondicionamentoFisico;
import bodyfitness.pessoas.cliente.caracteristicas.corporal.Indices;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Bodner do Rosário <luan.rosario.bodner@gmail.com>
 */
public class PainelClienteEditarIndices extends javax.swing.JFrame {

    /**
     * Creates new form ClienteAvaliação
     */
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    public PainelClienteEditarIndices(Long id) {
        initComponents();
        this.id = id;
        this.idTField.setText(id.toString());
        this.idTField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliaçãoPanel = new javax.swing.JPanel();
        imcLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        percentualGorduraIdealLabel = new javax.swing.JLabel();
        massaMagraLabel = new javax.swing.JLabel();
        percentualGorduraAtualLabel = new javax.swing.JLabel();
        massaGordaLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        imcTField = new javax.swing.JTextField();
        idTField = new javax.swing.JTextField();
        pgiTField = new javax.swing.JTextField();
        massaMagraTField = new javax.swing.JTextField();
        massaGordaTField = new javax.swing.JTextField();
        pdgiTField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        avaliaçãoPanel.setPreferredSize(new java.awt.Dimension(1000, 650));
        avaliaçãoPanel.setLayout(null);

        imcLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        imcLabel.setForeground(new java.awt.Color(254, 254, 254));
        imcLabel.setText("IMC :");
        avaliaçãoPanel.add(imcLabel);
        imcLabel.setBounds(60, 180, 60, 50);

        idLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(254, 254, 254));
        idLabel.setText("ID :");
        avaliaçãoPanel.add(idLabel);
        idLabel.setBounds(70, 280, 50, 50);

        percentualGorduraIdealLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        percentualGorduraIdealLabel.setForeground(new java.awt.Color(254, 254, 254));
        percentualGorduraIdealLabel.setText("P. Gordura Ideal :");
        avaliaçãoPanel.add(percentualGorduraIdealLabel);
        percentualGorduraIdealLabel.setBounds(60, 380, 200, 50);

        massaMagraLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        massaMagraLabel.setForeground(new java.awt.Color(254, 254, 254));
        massaMagraLabel.setText("Massa Magra :");
        avaliaçãoPanel.add(massaMagraLabel);
        massaMagraLabel.setBounds(510, 380, 160, 50);

        percentualGorduraAtualLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        percentualGorduraAtualLabel.setForeground(new java.awt.Color(254, 254, 254));
        percentualGorduraAtualLabel.setText("P. Gordura Ideal :");
        avaliaçãoPanel.add(percentualGorduraAtualLabel);
        percentualGorduraAtualLabel.setBounds(500, 180, 200, 50);

        massaGordaLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        massaGordaLabel.setForeground(new java.awt.Color(254, 254, 254));
        massaGordaLabel.setText("Massa Gorda :");
        avaliaçãoPanel.add(massaGordaLabel);
        massaGordaLabel.setBounds(510, 280, 160, 50);

        header.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        header.setForeground(new java.awt.Color(254, 254, 254));
        header.setText("Editar índices");
        header.setToolTipText("");
        avaliaçãoPanel.add(header);
        header.setBounds(390, 60, 240, 50);

        editarButton.setText("Editar");
        avaliaçãoPanel.add(editarButton);
        editarButton.setBounds(490, 530, 80, 50);

        imcTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imcTFieldActionPerformed(evt);
            }
        });
        editarButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt){
               editarButtonActionPerformed(evt);
           }
        });
        avaliaçãoPanel.add(imcTField);
        imcTField.setBounds(130, 180, 310, 50);
        avaliaçãoPanel.add(idTField);
        idTField.setBounds(130, 280, 310, 50);
        avaliaçãoPanel.add(pgiTField);
        pgiTField.setBounds(260, 380, 180, 50);
        avaliaçãoPanel.add(massaMagraTField);
        massaMagraTField.setBounds(670, 380, 270, 50);
        avaliaçãoPanel.add(massaGordaTField);
        massaGordaTField.setBounds(670, 280, 270, 50);
        avaliaçãoPanel.add(pdgiTField);
        pdgiTField.setBounds(700, 180, 240, 50);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/índice.jpg"))); // NOI18N
        image.setText("image");
        avaliaçãoPanel.add(image);
        image.setBounds(-50, -40, 1962, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avaliaçãoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //JOptionPane.showMessageDialog(null, "deu certo","Certo",JOptionPane.INFORMATION_MESSAGE);
        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.consultarPorId(this.getId());
        CondicionamentoFisico cond = new CondicionamentoFisico();
        cond.setComposicaoCorporal(new Indices());
        boolean hasId = false;
        try {
            if(cliente.getCondicionamentoFisico() != null) {
                hasId = true;
            }
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
        if(this.imcTField.getText().matches("[0-9][0-9]\\.[0-9][0-9]")) {
            cond.getComposicaoCorporal().setImc(Double.valueOf(this.imcTField.getText()));
            JOptionPane.showMessageDialog(null, "IMC alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if(this.massaGordaTField.getText().matches("[0-9][0-9]\\.[0-9][0-9]")) {
            cond.getComposicaoCorporal().setMassaGorda(Double.valueOf(this.massaGordaTField.getText()));
            JOptionPane.showMessageDialog(null, "massa gorda alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if(this.massaMagraTField.getText().matches("[0-9][0-9]\\.[0-9][0-9]")) {
            cond.getComposicaoCorporal().setMassaMagra(Double.valueOf(this.massaMagraTField.getText()));
            JOptionPane.showMessageDialog(null, "massa magra contráido alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if(this.pdgiTField.getText().matches("[0-9][0-9]\\.[0-9][0-9]")) {
            cond.getComposicaoCorporal().setPercentualGorduraIdeal(Double.valueOf(this.pdgiTField.getText()));
            JOptionPane.showMessageDialog(null, "percentual gordura ideal alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        if(this.pgiTField.getText().matches("[0-9][0-9]\\.[0-9][0-9]")) {
            cond.getComposicaoCorporal().setPercentualGorduraAtual(Double.valueOf(this.pgiTField.getText()));
            JOptionPane.showMessageDialog(null, "percentual gordura atual alterado", "confirmação", JOptionPane.INFORMATION_MESSAGE);
        }
        cliente.setCondicionamentoFisico(cond);
        dao.persist(cliente);
        JOptionPane.showMessageDialog(null, "Indices atualizados", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }
    private void imcTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imcTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imcTFieldActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelClienteEditarIndices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PainelClienteEditarIndices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avaliaçãoPanel;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel imcLabel;
    private javax.swing.JTextField imcTField;
    private javax.swing.JLabel massaGordaLabel;
    private javax.swing.JTextField massaGordaTField;
    private javax.swing.JLabel massaMagraLabel;
    private javax.swing.JTextField massaMagraTField;
    private javax.swing.JTextField pdgiTField;
    private javax.swing.JLabel percentualGorduraAtualLabel;
    private javax.swing.JLabel percentualGorduraIdealLabel;
    private javax.swing.JTextField pgiTField;
    // End of variables declaration//GEN-END:variables
}
