-- MySQL Script generated by MySQL Workbench
-- Seg 02 Mai 2016 19:59:28 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `Rua` INT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Número` VARCHAR(45) NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treino` (
  `Nome` VARCHAR(45) NOT NULL,
  `Series` INT NULL,
  `Repeticoes` INT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `Tipo` VARCHAR(45) NOT NULL,
  `HorarioInicio` DATE NULL,
  `HorarioTermino` DATE NULL,
  `Custo` DOUBLE NULL,
  PRIMARY KEY (`Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AvaliacaoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AvaliacaoCliente` (
  `Peso` DOUBLE NULL,
  `PGC` DOUBLE NULL,
  `AvaliacaoCliente` DATE NULL,
  `Responsavel` VARCHAR(45) NULL,
  `idAvaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAvaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Endereço_CEP` VARCHAR(45) NOT NULL,
  `Treino_Nome` VARCHAR(45) NOT NULL,
  `Aula_Tipo` VARCHAR(45) NOT NULL,
  `Mensalidade` DOUBLE NULL,
  `AvaliacaoCliente_idAvaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`, `Endereço_CEP`, `Treino_Nome`, `Aula_Tipo`, `AvaliacaoCliente_idAvaliacao`),
  INDEX `fk_Cliente_Endereço_idx` (`Endereço_CEP` ASC),
  INDEX `fk_Cliente_Treino1_idx` (`Treino_Nome` ASC),
  INDEX `fk_Cliente_Aula1_idx` (`Aula_Tipo` ASC),
  INDEX `fk_Cliente_AvaliacaoCliente1_idx` (`AvaliacaoCliente_idAvaliacao` ASC),
  CONSTRAINT `fk_Cliente_Endereço`
    FOREIGN KEY (`Endereço_CEP`)
    REFERENCES `mydb`.`Endereco` (`CEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Treino1`
    FOREIGN KEY (`Treino_Nome`)
    REFERENCES `mydb`.`Treino` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Aula1`
    FOREIGN KEY (`Aula_Tipo`)
    REFERENCES `mydb`.`Aula` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_AvaliacaoCliente1`
    FOREIGN KEY (`AvaliacaoCliente_idAvaliacao`)
    REFERENCES `mydb`.`AvaliacaoCliente` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CondicaoEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CondicaoEquipamento` (
  `Peso` INT NULL,
  `Estado` VARCHAR(45) NULL,
  `Responsável` VARCHAR(45) NULL,
  `Manutencao` DATE NULL,
  `Equipamento_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Equipamento_Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `Nome` INT NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Treino_Nome` VARCHAR(45) NOT NULL,
  `CondicaoEquipamento_Equipamento_Nome` INT NOT NULL,
  PRIMARY KEY (`Nome`, `CondicaoEquipamento_Equipamento_Nome`),
  INDEX `fk_Equipamento_Treino1_idx` (`Treino_Nome` ASC),
  INDEX `fk_Equipamento_CondicaoEquipamento1_idx` (`CondicaoEquipamento_Equipamento_Nome` ASC),
  CONSTRAINT `fk_Equipamento_Treino1`
    FOREIGN KEY (`Treino_Nome`)
    REFERENCES `mydb`.`Treino` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipamento_CondicaoEquipamento1`
    FOREIGN KEY (`CondicaoEquipamento_Equipamento_Nome`)
    REFERENCES `mydb`.`CondicaoEquipamento` (`Equipamento_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Nome` VARCHAR(45) NULL,
  `Salário` DOUBLE NULL,
  `Endereco_CEP` VARCHAR(45) NOT NULL,
  `Aula_Tipo` VARCHAR(45) NOT NULL,
  `IdFuncionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Endereco_CEP`, `Aula_Tipo`, `IdFuncionario`),
  INDEX `fk_Funcionario_Endereco1_idx` (`Endereco_CEP` ASC),
  INDEX `fk_Funcionario_Aula1_idx` (`Aula_Tipo` ASC),
  CONSTRAINT `fk_Funcionario_Endereco1`
    FOREIGN KEY (`Endereco_CEP`)
    REFERENCES `mydb`.`Endereco` (`CEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Aula1`
    FOREIGN KEY (`Aula_Tipo`)
    REFERENCES `mydb`.`Aula` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saida` (
  `Luz` DOUBLE NULL,
  `Agua` DOUBLE NULL,
  `Funcionarios` DOUBLE NULL,
  `IdSaida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdSaida`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
